# Generated by Django 2.1.5 on 2019-01-30 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='time',
        ),
        migrations.AddField(
            model_name='node',
            name='tx_since',
            field=models.DateField(default=datetime.date(2018, 1, 30)),
        ),
    ]
