# Generated by Django 2.1.5 on 2019-01-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0002_auto_20190130_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='minTx',
            field=models.IntegerField(default=1000000),
        ),
    ]
