# Generated by Django 2.1.5 on 2019-01-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0003_auto_20190130_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='tx_since',
            new_name='tx_Since',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='address',
            new_name='usdt_Address',
        ),
    ]
