# Generated by Django 2.1.5 on 2019-01-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0004_auto_20190130_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='usdt_Address',
            new_name='USDT_Address',
        ),
    ]
