# Generated by Django 2.1.5 on 2019-02-02 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdt', '0005_auto_20190130_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tx_Since',
            field=models.DateField(default=datetime.date(2018, 2, 2)),
        ),
    ]
