# Generated by Django 2.1.5 on 2019-02-02 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('USDT_Address', models.CharField(max_length=250)),
                ('minTx', models.IntegerField(default=1000000)),
                ('tx_Since', models.DateField(default=datetime.date(2018, 2, 2))),
            ],
        ),
    ]
