# Generated by Django 2.1.5 on 2019-02-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='USDT_Address',
            new_name='BTC_Address',
        ),
    ]
