# Generated by Django 2.1.5 on 2019-02-06 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0003_auto_20190202_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='tx_Since',
            field=models.DateField(default=datetime.date(2018, 2, 6)),
        ),
    ]
