# Generated by Django 2.1.5 on 2019-02-24 03:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0007_auto_20190219_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='category',
            field=models.CharField(blank=True, default='', max_length=36, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='node',
            name='tx_Since',
            field=models.DateField(default=datetime.date(2018, 2, 23)),
        ),
    ]
