# Generated by Django 2.1.5 on 2019-11-05 00:46

import coin.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='USDT', max_length=5, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9_ -]*$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9_ -]*$')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minBal', models.FloatField(default=-1)),
                ('maxBal', models.FloatField(default=100000000000000.0)),
                ('minTx', models.FloatField(default=-1)),
                ('maxTx', models.FloatField(default=100000000000000.0)),
                ('minTime', models.IntegerField(default=1230940800)),
                ('maxTime', models.IntegerField(default=10000000000.0)),
                ('minTotal', models.FloatField(default=-1)),
                ('maxTotal', models.FloatField(default=100000000000000.0)),
                ('minTxsNum', models.FloatField(default=-1)),
                ('maxTxsNum', models.FloatField(default=100000000000000.0)),
                ('minAvg', models.FloatField(default=-1)),
                ('maxAvg', models.FloatField(default=100000000000000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9_ -]*$')])),
                ('addr', models.CharField(max_length=34, validators=[django.core.validators.MinLengthValidator(34), django.core.validators.RegexValidator('^[A-Za-z0-9]*$'), coin.models.validate_addr])),
                ('minBal', models.FloatField(default=-1)),
                ('maxBal', models.FloatField(default=100000000000000.0)),
                ('minTx', models.FloatField(default=-1)),
                ('maxTx', models.FloatField(default=100000000000000.0)),
                ('minTime', models.IntegerField(default=1230940800)),
                ('maxTime', models.IntegerField(default=10000000000.0)),
                ('minTotal', models.FloatField(default=-1)),
                ('maxTotal', models.FloatField(default=100000000000000.0)),
                ('minTxsNum', models.FloatField(default=-1)),
                ('maxTxsNum', models.FloatField(default=100000000000000.0)),
                ('minAvg', models.FloatField(default=-1)),
                ('maxAvg', models.FloatField(default=100000000000000.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='coin.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9_ -]*$')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coin.Coin')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='coin.Session'),
        ),
    ]
