# Generated by Django 2.1.5 on 2019-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_auto_20191110_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='maxTime',
            field=models.CharField(default=10000000000.0, max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='minTime',
            field=models.CharField(default=1230940800, max_length=256),
        ),
    ]
