# Generated by Django 2.1.5 on 2019-12-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20191219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='maxTime',
            field=models.IntegerField(default=10000000000.0),
        ),
        migrations.AlterField(
            model_name='node',
            name='minTime',
            field=models.IntegerField(default=1230940800),
        ),
    ]
